before_script:
  - bash .gitlab-ci.sh

variables:
  MYSQL_DATABASE: database_name
  MYSQL_ROOT_PASSWORD: secret

phpunit:php5.6:mysql5.7:
  image: tetraweb/php:5.6
  services:
    - mysql:5.7
  script:
    - php vendor/bin/phpunit --colors --debug
    - script "php artisan dusk --colors --debug"

phpunit:php7.1:mysql5.7:
  image: tetraweb/php:7.1
  services:
    - mysql:5.7
  script:
    - php vendor/bin/phpunit --colors --debug
    - script "php artisan dusk --colors --debug"
